<?php 
/*
 * @author: Katarzyna Kajzar <k.kajzar@gmail.com>
 * created 2015-07-01
 */

 $title = 'Add new localization';
 $this->headTitle($title);
 ?>

 <p>
    <a href="<?= $this->url('localization', array('action' => 'index')); ?>">Back to all localizations.</a>
</p>

 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('localization', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name')).'<br />';
 echo $this->formRow($form->get('description')).'<br />';
 echo $this->formRow($form->get('address')).'<br />';
 echo $this->formRow($form->get('email')).'<br />';
 echo $this->formRow($form->get('date_from')).'<br />';
 echo $this->formRow($form->get('date_to')).'<br />';
 echo $this->formSubmit($form->get('submit')).'<br />';
 echo $this->form()->closeTag();

?>